### ISSUE TITLE
Obama pic gives error

### ISSUE THREAD

**Issue by michaelaye** [daleroberts/tv#2]
```bash
(stable) └─❱❱❱ tv -url https://github.com/jart/hiptext/blob/master/obama.jpg                                                1 ⏎  +5819 9:27 ❰─┘
Traceback (most recent call last):
  File "/Users/klay6683/bin/tv", line 309, in <module>
    show_url(url, **kwargs)
  File "/Users/klay6683/bin/tv", line 259, in show_url
    show_fd(gdal.Open(mmapfn), *args, **kwargs)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/osgeo/gdal.py", line 2943, in Open
    return _gdal.Open(*args)
RuntimeError: `/vsimem/97d993bcdb314feda6929c4b4ba4060e' not recognized as a supported file format.
```

Using iterm2.app v3.0.14 on macOS 10.11.6

**Comment by daleroberts** [comment]
Wrong URL, try this: `tv -url https://github.com/jart/hiptext/raw/master/obama.jpg`
